"""Added  release date to honorarium

Revision ID: 072128939aa7
Revises: e44585d13135
Create Date: 2024-06-05 00:08:23.430051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072128939aa7'
down_revision = 'e44585d13135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('honorarium_released_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('honorarium_released_date')

    # ### end Alembic commands ###
