"""Added forms fields to enrollments

Revision ID: 09f8efa0e2b8
Revises: d9f60960440b
Create Date: 2024-05-27 19:11:02.959148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f8efa0e2b8'
down_revision = 'd9f60960440b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form1path', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('form2path', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('form3path', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('form3path')
        batch_op.drop_column('form2path')
        batch_op.drop_column('form1path')

    # ### end Alembic commands ###
