"""Images now stored in folder.

Revision ID: 0d068b63db5c
Revises: d3d865780388
Create Date: 2024-04-02 21:15:32.839110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d068b63db5c'
down_revision = 'd3d865780388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filepath', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('receipt')
        batch_op.drop_column('receipt_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filename', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('receipt', sa.BLOB(), nullable=True))
        batch_op.drop_column('receipt_filepath')

    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=64), nullable=False),
    sa.Column('file', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
