"""Change academic year from int to string

Revision ID: 0f53945af61a
Revises: c521ca191ba2
Create Date: 2024-05-30 22:36:38.535873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f53945af61a'
down_revision = 'c521ca191ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=9),
               existing_nullable=True)
        batch_op.alter_column('semester',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Enum('1st', '2nd', 'Midyear'),
               existing_nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('payment', 'enrollment', 'enrolled', 're-enrollment', 'completion'),
               existing_nullable=False)
        batch_op.alter_column('academic_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=sa.String(length=9),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.Enum('payment', 'enrollment', 'enrolled', 're-enrollment', 'completion'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.Enum('1st', '2nd', 'Midyear'),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.String(length=9),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
