"""Added year_levels to college

Revision ID: 1e6e77c1673e
Revises: cb31b1e8e49f
Create Date: 2024-06-08 18:19:14.202598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6e77c1673e'
down_revision = 'cb31b1e8e49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_levels', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('year_levels')

    # ### end Alembic commands ###
