"""Added tup id column to students

Revision ID: 268d2c39b07f
Revises: ec3962248990
Create Date: 2024-05-16 16:48:29.777584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268d2c39b07f'
down_revision = 'ec3962248990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tup_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('tup_id')

    # ### end Alembic commands ###
