"""Added table instructor field to educational background

Revision ID: 26b872bdf606
Revises: 6d1adeed8a01
Create Date: 2024-06-01 00:50:43.620360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b872bdf606'
down_revision = '6d1adeed8a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educational_backgrounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_educational_backgrounds_instructor_instructors'), 'instructors', ['instructor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educational_backgrounds', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_educational_backgrounds_instructor_instructors'), type_='foreignkey')
        batch_op.drop_column('instructor')

    # ### end Alembic commands ###
