"""Added abbr column to programs

Revision ID: 47a80973d06c
Revises: aef65c5b8c24
Create Date: 2024-05-14 18:52:22.997942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a80973d06c'
down_revision = 'aef65c5b8c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbr', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('abbr')

    # ### end Alembic commands ###
