"""Added additional substatus for payment

Revision ID: 48ffb08e1f17
Revises: f1912dc256cb
Create Date: 2024-06-03 16:40:19.866598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ffb08e1f17'
down_revision = 'f1912dc256cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('payment', 'payment-pending', 'payment-rejected', 'enrollment', 'enrolled', 'graduate'),
               existing_nullable=False)
        batch_op.alter_column('semester',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Enum('1st', '2nd', 'Midyear'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.Enum('1st', '2nd', 'Midyear'),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.Enum('payment', 'payment-pending', 'payment-rejected', 'enrollment', 'enrolled', 'graduate'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
