"""Added colleges and programs tables

Revision ID: 5e5e81a5abe7
Revises: e82991fa10b9
Create Date: 2024-05-09 07:04:13.611204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5e81a5abe7'
down_revision = 'e82991fa10b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_program_id_programs'), 'programs', ['program_id'], ['id'])

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_programs_college_id_colleges'), 'colleges', ['college_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_programs_college_id_colleges'), type_='foreignkey')
        batch_op.drop_column('college_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_program_id_programs'), type_='foreignkey')
        batch_op.drop_column('program_id')

    # ### end Alembic commands ###
