"""Removed receipt filepath column for students

Revision ID: 69938074fb73
Revises: da929f6ad255
Create Date: 2024-05-31 04:27:58.263501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69938074fb73'
down_revision = 'da929f6ad255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('payment', 'enrollment', 'enrolled', 'graduate'),
               existing_nullable=False)
        batch_op.drop_column('application_document_filepath')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_document_filepath', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('progress',
               existing_type=sa.Enum('payment', 'enrollment', 'enrolled', 'graduate'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
