"""Added table education backgrounds

Revision ID: 6d1adeed8a01
Revises: 6a2f25c22a0d
Create Date: 2024-06-01 00:48:43.286370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1adeed8a01'
down_revision = '6a2f25c22a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('residency',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('local', 'foreign'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('residency',
               existing_type=sa.Enum('local', 'foreign'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
