"""Added college column to instructors

Revision ID: 88a08aa94c85
Revises: b64237f7e8ee
Create Date: 2024-05-31 01:26:22.462674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a08aa94c85'
down_revision = 'b64237f7e8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('honorarium',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('onprocess', 'released'),
               existing_nullable=True)

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', sa.Enum('COS', 'CIT', 'CIE'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_column('college')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('honorarium',
               existing_type=sa.Enum('onprocess', 'released'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
