"""Changed column course_id to class_id in table 'enrollment'

Revision ID: a288e40a746a
Revises: a62eadfd3f27
Create Date: 2024-04-09 02:08:59.884057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a288e40a746a'
down_revision = 'a62eadfd3f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['course_id'], ['id'])
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
