"""Images now stored in folder. (cont. 1)

Revision ID: a62eadfd3f27
Revises: 0d068b63db5c
Create Date: 2024-04-02 21:23:18.200364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62eadfd3f27'
down_revision = '0d068b63db5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_document_filepath', sa.String(length=64), nullable=True))
        batch_op.alter_column('receipt_filepath',
               existing_type=sa.BLOB(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_column('application_document')
        batch_op.drop_column('application_document_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_document_filename', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('application_document', sa.BLOB(), nullable=True))
        batch_op.alter_column('receipt_filepath',
               existing_type=sa.String(length=64),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.drop_column('application_document_filepath')

    # ### end Alembic commands ###
