"""Added academic year and semester columns

Revision ID: aef65c5b8c24
Revises: ea7eac2fe0c3
Create Date: 2024-05-14 17:15:26.305950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef65c5b8c24'
down_revision = 'ea7eac2fe0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.Enum('1st', '2nd'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('semester')
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###
