"""removed years and semesters from course curriculum

Revision ID: cff05892ff15
Revises: 1e6e77c1673e
Create Date: 2024-06-09 15:26:24.790403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff05892ff15'
down_revision = '1e6e77c1673e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_course_association', schema=None) as batch_op:
        batch_op.drop_column('semester')
        batch_op.drop_column('year_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_course_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_level', sa.VARCHAR(length=9), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.VARCHAR(length=3), nullable=True))

    # ### end Alembic commands ###
