"""Initial migration.

Revision ID: d3d865780388
Revises: 
Create Date: 2024-04-02 17:26:43.914068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d865780388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('receipt_filename', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('application_document', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('application_document_filename', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('application_document_filename')
        batch_op.drop_column('application_document')
        batch_op.drop_column('receipt_filename')
        batch_op.drop_column('receipt')

    # ### end Alembic commands ###
