"""Added dean and dept head to students table

Revision ID: d7b232f65ac5
Revises: cff05892ff15
Create Date: 2024-06-10 04:15:30.023802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b232f65ac5'
down_revision = 'cff05892ff15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dean', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('dept_head', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('dept_head')
        batch_op.drop_column('dean')

    # ### end Alembic commands ###
