"""Changed college column to college_id foreign key

Revision ID: da929f6ad255
Revises: 88a08aa94c85
Create Date: 2024-05-31 01:27:27.685382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da929f6ad255'
down_revision = '88a08aa94c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.alter_column('college',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_instructors_college_colleges'), 'colleges', ['college'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_instructors_college_colleges'), type_='foreignkey')
        batch_op.alter_column('college',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###
