"""Change residency to type of student

Revision ID: e44585d13135
Revises: 48ffb08e1f17
Create Date: 2024-06-03 18:39:22.622206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44585d13135'
down_revision = '48ffb08e1f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_student', sa.Enum('local', 'foreign'), nullable=True))
        batch_op.add_column(sa.Column('foreign_address', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('foreign_address')
        batch_op.drop_column('residency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residency', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('foreign_address', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('foreign_address')
        batch_op.drop_column('type_of_student')

    # ### end Alembic commands ###
