"""Added programs column for students

Revision ID: ea7eac2fe0c3
Revises: 5e5e81a5abe7
Create Date: 2024-05-14 17:06:24.203310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7eac2fe0c3'
down_revision = '5e5e81a5abe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_students_program_programs'), 'programs', ['program'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_program_programs'), type_='foreignkey')
        batch_op.drop_column('program')

    # ### end Alembic commands ###
