"""Changed exclusivity of educational backgrounds field

Revision ID: ffced365dacf
Revises: c9f9d57c069e
Create Date: 2024-06-05 12:59:09.282606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffced365dacf'
down_revision = 'c9f9d57c069e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educational_backgrounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_educational_backgrounds_instructor_instructors', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_educational_backgrounds_user_users'), 'users', ['user'], ['id'])
        batch_op.drop_column('instructor')

    with op.batch_alter_table('social_media_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_social_media_accounts_user_users'), 'users', ['user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_social_media_accounts_user_users'), type_='foreignkey')
        batch_op.drop_column('user')

    with op.batch_alter_table('educational_backgrounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_educational_backgrounds_user_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_educational_backgrounds_instructor_instructors', 'instructors', ['instructor'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###
